### ISSUE TITLE
Error in screensharing

### ISSUE THREAD

**Issue by Boopalan-M** [ttejas123/Video_Con#1]
Up to 5 users the screen sharing is correct when the 6th user connects the screen sharing is not visible to them and the videos are also get duplicated, 

Thanks in  advance..

**Comment by ttejas123** [comment]
1. If you want to use screenshare than first all this 5 or 6 users should be present in room. 

2. Screen share is dependent on user Video stream and than it will convert into screen share stream. So if user is not present before screen share starts than user can't see screen share, instead of that only previous video stream is visible.
